<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNz0kwqx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNz0kwqx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNz0kwqx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNz0kwqx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNz0kwqx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nz0kwqx',
    'container.build_id' => 'c1a8ba40',
    'container.build_time' => 1639141538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNz0kwqx');
