<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'articles' => [['nom', 'age'], ['_controller' => 'App\\Controller\\ArticlesController::index2'], [], [['variable', '/', '[^/]++', 'age', true], ['variable', '/', '[^/]++', 'nom', true], ['text', '/home']], [], []],
    'formulair' => [[], ['_controller' => 'App\\Controller\\FormulairController::index'], [], [['text', '/formulair']], [], []],
    'form' => [[], ['_controller' => 'App\\Controller\\FormulairController::index2'], [], [['text', '/form']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], []],
    'app_lucky_number' => [['max'], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['variable', '/', '[^/]++', 'max', true], ['text', '/lucky/number']], [], []],
    'app_lucky_index' => [[], ['_controller' => 'App\\Controller\\LuckyController::index'], [], [['text', '/index']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
